### ISSUE TITLE
Unable to go into debug mode/use commands on my single player server

### ISSUE THREAD

**Issue by Void-180** [Sketaful/Sketaful-s-Valheim-Adventure-Modpack#2]
ive been trying to get into debug mode to fixd a issue in my world but everytime i attempt to go into it or anyother command it comes up with 
![image](https://github.com/Sketaful/Sketaful-s-Valheim-Adventure-Modpack/assets/172191946/2f178fd8-ead2-4d01-a897-29438931ad8f)

**Comment by Sketaful** [comment]
You should already be in debug mode. I kinda forgot a mod activating it.
Don't know if that's the one making commands in console impossible to
execute but you should be able to run the commands in the chat starting
with a / before the command.

Use the console to see the info on running commands and use console to type
commands and see what arguments it support but execute them on chat should
work.

I'll look into it and will remove the mod I think messes it up in a future
update.

Den sön 9 juni 2024 15:43Void-180 ***@***.***> skrev:

**Comment by Sketaful** [comment]
Check if you have the Server Devcommands mod installed. I used it a while back but removed it but if you just updated you might still have it left hanging.

**Comment by Void-180** [comment]
i have it.
its working through the chat, thanks
