### ISSUE TITLE
Items disappearing from equipped section in inventory after loading into game.

### ISSUE THREAD

**Issue by Void-180** [Sketaful/Sketaful-s-Valheim-Adventure-Modpack#4]
Whenever I leave my game with stuff in my armour slots and the 123 numpad slots they will vanish the next time i load into the game. the only slot that does not do this is the utility slot.
![image](https://github.com/Sketaful/Sketaful-s-Valheim-Adventure-Modpack/assets/172191946/322a5dec-dfbd-4618-bb52-09f054d474de)

**Comment by Sketaful** [comment]
That is weird. The mod for the slots have safeguards against that so it
shouldn't be possible.

When you quit. You just logout through the menu?

Den sön 23 juni 2024 18:41Void-180 ***@***.***> skrev:

**Comment by Void-180** [comment]
When i go to log off i 1st save. then click log off so i go back to the menu screen. then i close valhiem.

**Comment by Sketaful** [comment]
That is strange. I have to look into it. I presume you play singleplayer? Try removing ServerCharacters and see if that fix it. 

If you could upload your log that'd be great.

**Comment by Sketaful** [comment]
What version of the modpack do you run? That inventory doesn't look right. It should have slots for rings and other things as well.
Check that it is running the latest version and if you've been playing the modpack a while, make a new profile in the modlauncher and make a clean install of the latest modpack and check if that fixes the problem.

Either you're running an old version of the modpack before I changed to the updated version of the mod or an update haven't deleted the old mods so you need to do a clean install of the latest. 

Or before you start the game, while in the launcher, write slot in the searchbar. If it finds a mod called extra slots or something like that you need to do a fresh install of the latest version of the modpack.

**Comment by Void-180** [comment]
OK that's good to know. its all good now
